# Generated by Django 2.2.6 on 2020-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servey_year', models.CharField(max_length=4, null=True, verbose_name='year')),
                ('uniclass', models.CharField(max_length=10, null=True, verbose_name='uni_class')),
                ('estclass', models.CharField(max_length=2, null=True, verbose_name='est_class')),
                ('province', models.CharField(max_length=4, null=True, verbose_name='province')),
                ('city', models.CharField(max_length=3, null=True, verbose_name='city')),
                ('university', models.CharField(max_length=50, null=True, verbose_name='uni_name')),
                ('campus_class', models.CharField(max_length=2, null=True, verbose_name='cam_class')),
                ('campus_location', models.CharField(max_length=10, null=True, verbose_name='cam_location')),
                ('depart_type', models.CharField(max_length=10, null=True, verbose_name='depart_type')),
                ('time', models.CharField(max_length=10, null=True, verbose_name='time')),
                ('depart_state', models.CharField(max_length=10, null=True, verbose_name='depart_state')),
                ('standard_max_field', models.CharField(max_length=20, null=True, verbose_name='max_field')),
                ('standard_mid_field', models.CharField(max_length=20, null=True, verbose_name='mid_field')),
                ('standard_min_field', models.CharField(max_length=20, null=True, verbose_name='min_field')),
                ('uni_field', models.CharField(max_length=20, null=True, verbose_name='uni_field')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='department_name')),
                ('uni_year', models.CharField(max_length=2, null=True, verbose_name='uni_year')),
                ('homepage', models.URLField(unique=True, verbose_name='homepage')),
            ],
        ),
    ]
