# Generated by Django 2.2.6 on 2020-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0002_uniinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniinfo',
            name='homepage',
        ),
    ]
