# Generated by Django 2.2.6 on 2020-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0003_remove_uniinfo_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniinfo',
            name='uni_code',
            field=models.IntegerField(null=True, verbose_name='uni_code'),
        ),
    ]
