# Generated by Django 2.2.6 on 2020-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0005_standardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardinfo',
            name='list_max',
            field=models.CharField(max_length=20, null=True, verbose_name='max_field'),
        ),
    ]
