# Generated by Django 2.2.6 on 2020-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0006_standardinfo_list_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniinfo',
            name='campus_class',
            field=models.CharField(max_length=5, null=True, verbose_name='cam_class'),
        ),
    ]
