# Generated by Django 2.2.6 on 2020-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0007_auto_20200629_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniinfo',
            name='campus_class',
            field=models.CharField(max_length=15, null=True, verbose_name='cam_class'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='campus_location',
            field=models.CharField(max_length=20, null=True, verbose_name='cam_location'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='depart_type',
            field=models.CharField(max_length=20, null=True, verbose_name='depart_type'),
        ),
    ]
