# Generated by Django 2.2.6 on 2020-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0008_auto_20200629_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniinfo',
            name='depart_type',
            field=models.CharField(max_length=50, null=True, verbose_name='depart_type'),
        ),
    ]
