# Generated by Django 2.2.6 on 2020-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0009_auto_20200629_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniinfo',
            name='standard_max_field',
            field=models.CharField(max_length=30, null=True, verbose_name='max_field'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='standard_mid_field',
            field=models.CharField(max_length=30, null=True, verbose_name='mid_field'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='standard_min_field',
            field=models.CharField(max_length=30, null=True, verbose_name='min_field'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='uni_field',
            field=models.CharField(max_length=30, null=True, verbose_name='uni_field'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='uni_year',
            field=models.CharField(max_length=20, null=True, verbose_name='uni_year'),
        ),
    ]
