# Generated by Django 2.2.6 on 2020-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_depart_site', '0010_auto_20200629_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniinfo',
            name='campus_class',
            field=models.CharField(max_length=150, null=True, verbose_name='cam_class'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='campus_location',
            field=models.CharField(max_length=200, null=True, verbose_name='cam_location'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='depart_state',
            field=models.CharField(max_length=100, null=True, verbose_name='depart_state'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='estclass',
            field=models.CharField(max_length=20, null=True, verbose_name='est_class'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='province',
            field=models.CharField(max_length=40, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='servey_year',
            field=models.CharField(max_length=40, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='uniinfo',
            name='uniclass',
            field=models.CharField(max_length=100, null=True, verbose_name='uni_class'),
        ),
    ]
